// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQZ7-EF_gFWT_SfXCpoWaBMEeoB7ifDPo',
    appId: '1:1021637563714:web:ac3cad013d78ec4383a4db',
    messagingSenderId: '1021637563714',
    projectId: 'corealingo-proyecto',
    authDomain: 'corealingo-proyecto.firebaseapp.com',
    storageBucket: 'corealingo-proyecto.appspot.com',
    measurementId: 'G-HK439NR4W2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCibz-6akhj2X6YMPtmYlilkq19hoHum84',
    appId: '1:1021637563714:android:3084fd128d33850e83a4db',
    messagingSenderId: '1021637563714',
    projectId: 'corealingo-proyecto',
    storageBucket: 'corealingo-proyecto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRtv8iUTW4KKhw-QTFsZw3hr1Xea0XikM',
    appId: '1:1021637563714:ios:41582bb8de24271883a4db',
    messagingSenderId: '1021637563714',
    projectId: 'corealingo-proyecto',
    storageBucket: 'corealingo-proyecto.appspot.com',
    iosBundleId: 'com.example.corealingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRtv8iUTW4KKhw-QTFsZw3hr1Xea0XikM',
    appId: '1:1021637563714:ios:41582bb8de24271883a4db',
    messagingSenderId: '1021637563714',
    projectId: 'corealingo-proyecto',
    storageBucket: 'corealingo-proyecto.appspot.com',
    iosBundleId: 'com.example.corealingo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQZ7-EF_gFWT_SfXCpoWaBMEeoB7ifDPo',
    appId: '1:1021637563714:web:ac0ee6013dcdb64383a4db',
    messagingSenderId: '1021637563714',
    projectId: 'corealingo-proyecto',
    authDomain: 'corealingo-proyecto.firebaseapp.com',
    storageBucket: 'corealingo-proyecto.appspot.com',
    measurementId: 'G-T7KQCWCMEF',
  );
}
